# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        avatar:
            quality: 75
            cache: ~
            filters:
                thumbnail: { size: [120, 120], mode: outbound }
