vich_uploader:
    db_driver: orm

    mappings:
        post_picture:
            uri_prefix: '%uploads_path%'
            upload_destination: '%kernel.project_dir%/public/%uploads_path%'

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        profile_picture:
            uri_prefix: '%profile_path%'
            upload_destination: '%kernel.project_dir%/public/%profile_path%'

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

    
        